apiVersion: v1
kind: Secret
metadata:
  name: example-creds
  namespace: crossplane-system
type: Opaque
stringData:
  redis-password: password_123!
  credentials: |
    {
      "secret_id": "xxxxxxxxxxx",
      "secret_key": "xxxxxxxxxx",
      "region": "ap-hongkong"
    }
